name = "campus-equipment-booking-api"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[[d1_databases]]
binding = "DB"
database_name = "booking_db"
database_id = "769af00f-70e3-4b1c-829e-321ab0f7130d"
